
services:
  pdg-backend:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=pdg
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/var/www
    networks:
      - pdg-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdg
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pdg-network

  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    networks:
      - pdg-network

volumes:
  mysql_data:

networks:
  pdg-network:
    driver: bridge
